sudo: required
services:
    - docker

before_install:
    - docker build -t mozyk27/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mozyk27/react-test npm test -- --coverage

after_success:
    - docker build -t mozyk27/multi-client ./client
    - docker build -t mozyk27/multi-nginx ./nginx
    - docker build -t mozyk27/multi-server ./server
    - docker build -t mozyk27/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
    # Take those images and push them into Docker Hub
    - docker push mozyk27/multi-client
    - docker push mozyk27/multi-nginx
    - docker push mozyk27/multi-server
    - docker push mozyk27/multi-worker
